name: sirat_noor
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  lottie: ^3.3.0
  smooth_page_indicator: ^1.2.0+3

  connectivity_plus: ^5.0.2
  intl: ^0.20.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_qiblah: ^3.0.4
  flutter_svg: ^2.0.5
  geolocator: ^13.0.1
  flutter_tts: ^4.2.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  translator: ^1.0.3+1

  #Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/content/
